List<String> streetpuds = [
  'assets/images/street_foods/bananaq.png',
  'assets/images/street_foods/bbq.png',
  'assets/images/street_foods/dugo.png',
  'assets/images/street_foods/hakdog.png',
  'assets/images/street_foods/isaw.png',
  'assets/images/street_foods/kamoteq.png',
  'assets/images/street_foods/kwek.png',
  'assets/images/street_foods/paa_manacc.png',
  'assets/images/street_foods/bananaq.png',
  'assets/images/street_foods/bbq.png',
  'assets/images/street_foods/dugo.png',
  'assets/images/street_foods/hakdog.png',
  'assets/images/street_foods/isaw.png',
  'assets/images/street_foods/kamoteq.png',
  'assets/images/street_foods/kwek.png',
  'assets/images/street_foods/paa_manacc.png',
];

List<String> putahe = [
  'assets/images/putahes/adobo.png',
  'assets/images/putahes/bulalo.png',
  'assets/images/putahes/caldereta.png',
  'assets/images/putahes/dinuguan.png',
  'assets/images/putahes/karekare.png',
  'assets/images/putahes/pinakbet.png',
  'assets/images/putahes/sinigang.png',
  'assets/images/putahes/sisig.png',
  'assets/images/putahes/adobo.png',
  'assets/images/putahes/bulalo.png',
  'assets/images/putahes/caldereta.png',
  'assets/images/putahes/dinuguan.png',
  'assets/images/putahes/karekare.png',
  'assets/images/putahes/pinakbet.png',
  'assets/images/putahes/sinigang.png',
  'assets/images/putahes/sisig.png',
];

List<String> memes = [
  'assets/images/memes/advance.png',
  'assets/images/memes/arlene.png',
  'assets/images/memes/bong.png',
  'assets/images/memes/kris.png',
  'assets/images/memes/kween.png',
  'assets/images/memes/listen.png',
  'assets/images/memes/otlum.png',
  'assets/images/memes/sumakses.png',
  'assets/images/memes/advance.png',
  'assets/images/memes/arlene.png',
  'assets/images/memes/bong.png',
  'assets/images/memes/kris.png',
  'assets/images/memes/kween.png',
  'assets/images/memes/listen.png',
  'assets/images/memes/otlum.png',
  'assets/images/memes/sumakses.png',
];

List<String> maligno = [
  'assets/images/maligno/kapre.png',
  'assets/images/maligno/manananggal.png',
  'assets/images/maligno/nuno.png',
  'assets/images/maligno/santelmo.png',
  'assets/images/maligno/syokoy.png',
  'assets/images/maligno/tikbalang.png',
  'assets/images/maligno/tiyanak.png',
  'assets/images/maligno/white_lady.png',
  'assets/images/maligno/kapre.png',
  'assets/images/maligno/manananggal.png',
  'assets/images/maligno/nuno.png',
  'assets/images/maligno/santelmo.png',
  'assets/images/maligno/syokoy.png',
  'assets/images/maligno/tikbalang.png',
  'assets/images/maligno/tiyanak.png',
  'assets/images/maligno/white_lady.png',
];
